name: Scan Docker image

inputs:
  image-id:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  wiz-project-id:
    required: true
    type: string
  dockerfile-path:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Scan DockerFile
      if: ${{ env.DISABLE_WIZ != 'true' }}
      run: ./wizcli iac scan --name ${{ inputs.image-id }}:${{ inputs.image-tag }} --path ${{ inputs.dockerfile-path }} --types Dockerfile --project ${{ inputs.wiz-project-id }}
      shell: bash
