name: Install Wiz CLI

description: Install the Wiz CLI

runs:
  using: "composite"
  steps:
    - name: Download Wiz CLI
      if: ${{ env.DISABLE_WIZ != 'true' }}
      run: |
        curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64

        # Import the public key
        curl -Lo public_key.asc https://downloads.wiz.io/wizcli/public_key.asc
        gpg --import public_key.asc

        # Download files to perform signature verification
        curl -Lo /tmp/wizcli-sha256 https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256
        curl -Lo /tmp/wizcli-sha256.sig https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256.sig

        # Verify signature
        gpg --verify /tmp/wizcli-sha256.sig /tmp/wizcli-sha256

        # Verify SHA256
        echo "$(cat /tmp/wizcli-sha256) wizcli" | sha256sum --check
        chmod +x wizcli
        ./wizcli version
      shell: bash

    - name: Add Wiz CLI to .dockerignore
      if: ${{ env.DISABLE_WIZ != 'true' }}
      run: |
        echo "" >> .dockerignore
        echo "wizcli" >> .dockerignore
      shell: bash
