name: Lint Dockerfile

description: Lint a Dockerfile using Hadolint and ShellCheck

inputs:
  dockerfile-path:
    required: true
    type: string
  ignore-linting-rules:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.dockerfile-path }}
        ignore: ${{ inputs.ignore-linting-rules }}

    - name: ShellCheck
      run: |
        # [ -d "./bin" ] && shellcheck --external-sources --exclude=SC1091 ./bin/*
        shellcheck --external-sources --exclude=SC2148 ${{ inputs.dockerfile-path }}
      shell: bash
