name: Remove untagged container images

inputs:
  image-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Delete untagged images
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.request("GET /orgs/${{ github.repository_owner }}/packages/container/${{ inputs.image-name }}/versions", {
              per_page: 100
          });
          for(version of response.data) {
              if (version.metadata.container.tags.length == 0 && version.name !== "latest" && version.name !== "preview") {
                  console.log("Delete " + version.id)

                  const deleteResponse = await github.request("DELETE /orgs/${{ github.repository_owner }}/packages/container/${{ inputs.image-name }}/versions/" + version.id, { });
                  console.log("status " + deleteResponse.status)
              }
          }
      shell: bash