name: Get version tag

outputs:
  version-tag:
    description: "Version tag"
    value: ${{ steps.version-tag.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - id: version-tag
      name: Get tag from branch, tag or release
      run: |
        echo "github.ref:                   ${{ github.ref }}"
        echo "github.ref_name:              ${{ github.ref_name }}"
        echo "github.event.ref:             ${{ github.event.ref }}"

        # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        VERSION=$(echo "${{ github.ref_name }}" | sed -e 's,/,-,g')
        echo "Basic version:                $VERSION"

        # Strip "v" prefix from tag name
        [[ "${{ github.ref_type }}" == "tag" ]] && VERSION=$(echo "$VERSION" | sed -e 's/^v//')
        echo "Tag version without v prefix: $VERSION"

        CALVER=$(date +%y.%m.%d).${{ github.run_number }}
        echo "Calver:                       $CALVER"
        CALVER_ALT_1=$(date +%y.%m.%d).$(git rev-list HEAD --count)
        echo "Calver alt 1:                 $CALVER_ALT_1"
        CALVER_ALT_2=$(git log -1 --date=format:"%y.%m.%d" --format="%ad").$(git rev-list HEAD --count)
        echo "Calver alt 2:                 $CALVER_ALT_2"
        [ "$VERSION" == "main" ] && VERSION=$CALVER
        echo "Final version:                $VERSION"

        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash