name: Scan Docker image

description: Scan a Docker image for vulnerabilities using Wiz

inputs:
  image-id:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  wiz-client-id:
    required: true
    type: string
  wiz-client-secret:
    required: true
    type: string
  wiz-project-id:
    required: true
    type: string
  dockerfile-directory:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Scan DockerFile
      if: ${{ env.DISABLE_WIZ != 'true' }}
      run: ./wizcli iac scan --name ${{ inputs.image-id }}:${{ inputs.image-tag }} --path ${{ inputs.dockerfile-directory }} --types Dockerfile --client-id ${{ inputs.wiz-client-id }} --client-secret ${{ inputs.wiz-client-secret }} --projects ${{ inputs.wiz-project-id }}
      shell: bash
